spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: hldmurder
    password: Hldmurder123
    url: jdbc:mysql://rm-bp12qqwda0d908hl1no.mysql.rds.aliyuncs.com:3306/crm
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true